### ISSUE TITLE
`BUILD_ARGS` in task `buildah` does nothing

### ISSUE THREAD

**Issue by domq** [openshift-pipelines/task-containers#124]
What I tried: created a Tekton `Pipeline` that goes something like

```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: wp-base
  namespace: "wordpress-test"
spec:
  params:
    - name: quay-repo
      description: The hostname of the Quay repository to push to
      default: "quay-its.epfl.ch"
    - name: next-build-id
      description: "Sequence number of the next build to push to Quay"
  workspaces:
    - name: shared-workspace
    - name: dockerconfig
  tasks:
    - name: git-clone
      taskRef:
        kind: Task
        name: git-clone
      params:
        - name: url
          value: https://github.com/epfl-si/wp-ops
      workspaces:
      - name: output
        workspace: shared-workspace
    - name: build
      runAfter: [git-clone]
      taskRef:
        kind: Task
        name: buildah
      params:
        - name: IMAGE
          value: "$(params.quay-repo)/{{ quay_organization }}/wp-base:2025-$(params.next-build-id)"
        - name: CONTEXT
          value: "docker/wp-base"
        - name: VERBOSE
          value: "true"
        - name: BUILD_ARGS
          value:
          - AWS_ACCESS_KEY_ID=_____________
          - AWS_SECRET_ACCESS_KEY=_______________
      workspaces:
      - name: source
        workspace: shared-workspace

```

What I expected to happen: as per the parameter list of https://github.com/openshift-pipelines/tektoncd-catalog/raw/p/tasks/task-buildah/0.6.0/task-buildah.yaml I thought that each entry in `BUILD_ARG` would be turned into a `--build-arg=` on the Buildah command line.

What happens instead:

```
+ phase 'Building build args'
+ echo '---> Phase: Building build args...'
---> Phase: Building build args...
+ BUILD_ARGS=()
+ [[ false == \t\r\u\e ]]
+ ENTITLEMENT_VOLUME=
+ [[ false == \t\r\u\e ]]
+ phase 'Building '\''quay-its.epfl.ch/svc0041/wp-base:2025-48'\'' based on '\''/workspace/source/docker/wp-base/./Dockerfile'\'''
```
