### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by otaviof** [openshift-pipelines/task-containers#19]
The `s2i` build workflow supports setting environment variables:

```
$ s2i build --help |grep env
  -e, --env string                       Specify an single environment variable in NAME=VALUE format
  -E, --environment-file string          Specify the path to the file with environment
```

S2I Tasks rendered by this project should leverage the setting, like for instance on [task-buildpacks repository `ENV_VARS` param][taskBuildpacksParams].

A practical approach is receiving the params via STDIN and loop over the key-value pairs:

```yaml
steps:
  - name: example
    args: [ "$(params.ENV_VARS[*])" ]
```

Then, on `s2i-generate.sh` script can loop over the arguments to store on a file, for instance:

```bash
for kv in "${@}"; do
    # ...
done
```

The set of key-value should be stored on a temporary location (`/s2i-generate/s2i.env`?), informed to `s2i` using `--environment-file` flag.

[taskBuildpacksParams]: https://github.com/openshift-pipelines/task-buildpacks#params

**Comment by otaviof** [comment]
Example type `array` param:

```yaml
- name: ENV_VARS
  type: array
  description: Environment variables to set during _build-time_.
  default: []
```
